// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdCiqYva4ltxl8HAJmhN-golF_pQOQ3c',
    appId: '1:287016865087:web:f97407f59ba8f3f134178a',
    messagingSenderId: '287016865087',
    projectId: 'liaron-soundimplosion',
    authDomain: 'liaron-soundimplosion.firebaseapp.com',
    storageBucket: 'liaron-soundimplosion.firebasestorage.app',
    measurementId: 'G-NLJGMN072Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMiYmcHhnSNdspTVmYHB6-UZ_foo8bKbs',
    appId: '1:287016865087:android:9a638ce3bf4cc2ce34178a',
    messagingSenderId: '287016865087',
    projectId: 'liaron-soundimplosion',
    storageBucket: 'liaron-soundimplosion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOGP_yZT0wizMVAkH4fMjPPT4yGaehGA',
    appId: '1:287016865087:ios:361220a29798c3c034178a',
    messagingSenderId: '287016865087',
    projectId: 'liaron-soundimplosion',
    storageBucket: 'liaron-soundimplosion.firebasestorage.app',
    iosBundleId: 'it.sinnodel.soundimplosion',
  );
}
